apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-uploader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-uploader
  template:
    metadata:
      labels:
        app: rag-uploader
    spec:
      containers:
        - name: rag-uploader
          image: adnantd/rag-uploader
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medbot-secret
                  key: GOOGLE_API_KEY
            - name: CONNECTION_STRING
              value: 'postgresql+psycopg2://admin:admin@postgres-service:5432/vectordb'
            - name: CONNECTION_NAME
              value: 'vectordb'
---
apiVersion: v1
kind: Service
metadata:
  name: rag-uploader-service
spec:
  selector:
    app: rag-uploader
  ports:
    - name: rag-uploader
      protocol: TCP
      port: 8000
      targetPort: 80
